### PR TITLE
Fix cancel order in open orders table

### LINKED ISSUE #178: Labeling
Invest -> Subscribe
(Maybe remove the participation word at all)

Share price -> NAV/unit (share price * 100)

cc @perhamgirl

### PR DESCRIPTION
**Pull request by jennazenk**
### Changed
- [Label change] Invest -> Redeem
- Melon.js version bump 0.6.22

### Fixed
- cancel order in open orders table 
- Closes #178

### CODE REVIEW

File: src/components/pages/Ranking.jsx [hunk 1]
```diff
@@ -57,22 +58,20 @@ const Ranking = ({
             onClick={() =>
               ordering === "+price"
                 ? setOrdering("-price")
-                : setOrdering("+price")
-            }
+                : setOrdering("+price")}
           >
             {ordering === "+price" || ordering === "-price" ? (
-              <span style={activeStyle}>Share Price</span>
+              <span style={activeStyle}>Share price</span>
```
Comment (schmidsi) [inline src/components/pages/Ranking.jsx]: Why price with lowercase? It's a title/name, no?
